.tables
.data

USE VV_COORDENADAS;
--------------------------------------------------USUARIO VELASTEGUI---------------------------------------------
DROP TABLE CEDULAVELASTEGUI;
CREATE TABLE CEDULAVELASTEGUI
(
    CAP             VARCHAR(25)
    ,GEO            VARCHAR(25)
    ,TIPO_ARSENAL   VARCHAR(25)
);

--1754644415
INSERT INTO CEDULAVELASTEGUI (CAP, GEO, TIPO_ARSENAL) VALUES ('5', 'GPS6', 'bct');
INSERT INTO CEDULAVELASTEGUI (CAP, GEO, TIPO_ARSENAL) VALUES ('1', 'GPS4', 'bc');
INSERT INTO CEDULAVELASTEGUI (CAP, GEO, TIPO_ARSENAL) VALUES ('4', 'GPS9', 'acd');
INSERT INTO CEDULAVELASTEGUI (CAP, GEO, TIPO_ARSENAL) VALUES ('4', 'GPS4', 'acd');
INSERT INTO CEDULAVELASTEGUI (CAP, GEO, TIPO_ARSENAL) VALUES ('4', 'GPS2', 'acd');
INSERT INTO CEDULAVELASTEGUI (CAP, GEO, TIPO_ARSENAL) VALUES ('6', 'GPS9', 'act');
INSERT INTO CEDULAVELASTEGUI (CAP, GEO, TIPO_ARSENAL) VALUES ('4', 'GPS5', 'acd');
INSERT INTO CEDULAVELASTEGUI (CAP, GEO, TIPO_ARSENAL) VALUES ('5', 'GPS2', 'bct');
INSERT INTO CEDULAVELASTEGUI (CAP, GEO, TIPO_ARSENAL) VALUES ('7', 'GPS7', 'aaabbct');
INSERT INTO CEDULAVELASTEGUI (CAP, GEO, TIPO_ARSENAL) VALUES ('1', 'GPS1', 'bc');
SELECT * FROM CEDULAVELASTEGUI;

--------------------------------------------------USUARIO VILLARREAL---------------------------------------------
DROP TABLE CEDULAVILLARREAL;
CREATE TABLE CEDULAVILLARREAL
(
    CAP             VARCHAR(25)
    ,GEO            VARCHAR(25)
    ,TIPO_ARSENAL   VARCHAR(25)
);

--1752817799
INSERT INTO CEDULAVILLARREAL (CAP, GEO, TIPO_ARSENAL) VALUES ('9', 'GPS1', 'aaabbcd');
INSERT INTO CEDULAVILLARREAL (CAP, GEO, TIPO_ARSENAL) VALUES ('9', 'GPS5', 'aaabbcd');
INSERT INTO CEDULAVILLARREAL (CAP, GEO, TIPO_ARSENAL) VALUES ('7', 'GPS5', 'aaabbct');
INSERT INTO CEDULAVILLARREAL (CAP, GEO, TIPO_ARSENAL) VALUES ('7', 'GPS0', 'aaabbct');
INSERT INTO CEDULAVILLARREAL (CAP, GEO, TIPO_ARSENAL) VALUES ('1', 'GPS6', 'ab');
INSERT INTO CEDULAVILLARREAL (CAP, GEO, TIPO_ARSENAL) VALUES ('8', 'GPS7', 'abbccdt');
INSERT INTO CEDULAVILLARREAL (CAP, GEO, TIPO_ARSENAL) VALUES ('2', 'GPS2', 'ac');
INSERT INTO CEDULAVILLARREAL (CAP, GEO, TIPO_ARSENAL) VALUES ('5', 'GPS5', 'bct');
INSERT INTO CEDULAVILLARREAL (CAP, GEO, TIPO_ARSENAL) VALUES ('7', 'GPS7', 'aaabbct');
INSERT INTO CEDULAVILLARREAL (CAP, GEO, TIPO_ARSENAL) VALUES ('1', 'GPS1', 'ab');
SELECT * FROM CEDULAVILLARREAL;

---------------------------------------TABLA PARA LOGIN-----------------------------------------
DROP TABLE CREDENCIALES;
CREATE TABLE CREDENCIALES
(
     USUARIO     VARCHAR(25);
    ,CONTRASEÑA  VARCHAR(25);
);

INSERT INTO CREDENCIALES (USUARIO, CONTRASEÑA) VALUES ('Profe', '81dc9bdb52d04dc20036dbd8313ed055');
SELECT * FROM CREDENCIALES;