.version
.database
.show
.tables


--USE COORDENADAS;
--------------------------------------------------USUARIO VELASTEGUI---------------------------------------------
DROP TABLE VV_COORDENADAS;
CREATE TABLE VV_COORDENADAS
(
    VVCAP             VARCHAR(25)
    ,VVGEO            VARCHAR(25)
    ,VVTIPO_ARSENAL   VARCHAR(25)
)

--1754644415
INSERT INTO VV_COORDENADAS (VVCAP, VVGEO, VVTIPO_ARSENAL) VALUES ('5', 'GPS6', 'bct');
INSERT INTO VV_COORDENADAS (VVCAP, VVGEO, VVTIPO_ARSENAL) VALUES ('1', 'GPS4', 'bc');
INSERT INTO VV_COORDENADAS (VVCAP, VVGEO, VVTIPO_ARSENAL) VALUES ('4', 'GPS9', 'acd');
INSERT INTO VV_COORDENADAS (VVCAP, VVGEO, VVTIPO_ARSENAL) VALUES ('4', 'GPS4', 'acd');
INSERT INTO VV_COORDENADAS (VVCAP, VVGEO, VVTIPO_ARSENAL) VALUES ('4', 'GPS2', 'acd');
INSERT INTO VV_COORDENADAS (VVCAP, VVGEO, VVTIPO_ARSENAL) VALUES ('6', 'GPS9', 'act');
INSERT INTO VV_COORDENADAS (VVCAP, VVGEO, VVTIPO_ARSENAL) VALUES ('4', 'GPS5', 'acd');
INSERT INTO VV_COORDENADAS (VVCAP, VVGEO, VVTIPO_ARSENAL) VALUES ('5', 'GPS2', 'bct');
INSERT INTO VV_COORDENADAS (VVCAP, VVGEO, VVTIPO_ARSENAL) VALUES ('7', 'GPS7', 'aaabbct');
INSERT INTO VV_COORDENADAS (VVCAP, VVGEO, VVTIPO_ARSENAL) VALUES ('1', 'GPS1', 'bc');

--------------------------------------------------USUARIO VILLARREAL---------------------------------------------

--1752817799
INSERT INTO VV_COORDENADAS (VVCAP, VVGEO, VVTIPO_ARSENAL) VALUES ('9', 'GPS1', 'aaabbcd');
INSERT INTO VV_COORDENADAS (VVCAP, VVGEO, VVTIPO_ARSENAL) VALUES ('9', 'GPS5', 'aaabbcd');
INSERT INTO VV_COORDENADAS (VVCAP, VVGEO, VVTIPO_ARSENAL) VALUES ('7', 'GPS5', 'aaabbct');
INSERT INTO VV_COORDENADAS (VVCAP, VVGEO, VVTIPO_ARSENAL) VALUES ('7', 'GPS0', 'aaabbct');
INSERT INTO VV_COORDENADAS (VVCAP, VVGEO, VVTIPO_ARSENAL) VALUES ('1', 'GPS6', 'ab');
INSERT INTO VV_COORDENADAS (VVCAP, VVGEO, VVTIPO_ARSENAL) VALUES ('8', 'GPS7', 'abbccdt');
INSERT INTO VV_COORDENADAS (VVCAP, VVGEO, VVTIPO_ARSENAL) VALUES ('2', 'GPS2', 'ac');
INSERT INTO VV_COORDENADAS (VVCAP, VVGEO, VVTIPO_ARSENAL) VALUES ('5', 'GPS5', 'bct');
INSERT INTO VV_COORDENADAS (VVCAP, VVGEO, VVTIPO_ARSENAL) VALUES ('7', 'GPS7', 'aaabbct');
INSERT INTO VV_COORDENADAS (VVCAP, VVGEO, VVTIPO_ARSENAL) VALUES ('1', 'GPS1', 'ab');
SELECT * FROM VV_COORDENADAS;

---------------------------------------TABLA PARA LOGIN-----------------------------------------
DROP TABLE CREDENCIALES;
CREATE TABLE CREDENCIALES
(
    VVUSUARIO     VARCHAR(25)
    ,VVCONTRASENA  VARCHAR(25)
)

INSERT INTO CREDENCIALES (VVUSUARIO, VVCONTRASENA) VALUES ('Profe', '81dc9bdb52d04dc20036dbd8313ed055');
INSERT INTO CREDENCIALES (VVUSUARIO, VVCONTRASENA) VALUES ('francis.velastegui@epn.edu.ec', '5a97e3b6bc181e4c82b483f787510f2e');
INSERT INTO CREDENCIALES (VVUSUARIO, VVCONTRASENA) VALUES ('carlos.villarreal01@epn.edu.ec', '3a7ff58156d65078f2860597d86e12e8');

SELECT * FROM CREDENCIALES
